<?php

namespace Database\Seeders;

use App\Http\Services\JsonService;
use App\Models\AdminMenu;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdminMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $tableNames = config('dbtables.table_names');

        if (empty($tableNames)) {
            throw new \Exception('Error: config/permission.php not loaded. Run [php artisan config:clear] and try again.');
        }
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table($tableNames['admin_menus'])->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $admin_menus = [
            [
                'id' => 1,
                'menu_name' => 'Dashboard',
                'icon_class' => 'fas fa-tachometer-alt',
                'parent_id' => 0,
                's_order' => 1,
                'class_id' => 'title',
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 1,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 2,
                'menu_name' => 'CMS',
                'icon_class' => 'fas fa-folder-open',
                'parent_id' => 0,
                's_order' => 2,
                'class_id' => 'title',
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 3,
                'menu_name' => 'ACL',
                'icon_class' => 'fas fa-folder-open',
                'parent_id' => 2,
                's_order' => 3,
                'class_id' => 'title',
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-22 13:54:40',
                'updated_at' => '2023-11-22 13:54:40'
            ],
            [
                'id' => 4,
                'menu_name' => 'Access List',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 3,
                's_order' => 4,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 2,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-16 23:10:33'
            ],
            [
                'id' => 5,
                'menu_name' => 'Admin Menu',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 3,
                's_order' => 5,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 16,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 6,
                'menu_name' => 'Role Management',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 3,
                's_order' => 6,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 6,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 7,
                'menu_name' => 'Assign User Access',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 3,
                's_order' => 7,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 12,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 18:15:15'
            ],
            [
                'id' => 8,
                'menu_name' => 'Permission',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 3,
                's_order' => 8,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 9,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 9,
                'menu_name' => 'Manage Dept User',
                'icon_class' => 'fas fa-folder-open',
                'parent_id' => 2,
                's_order' => 10,
                'class_id' => 'title',
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-30 16:54:49'
            ],
            [
                'id' => 10,
                'menu_name' => 'Manage User',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 9,
                's_order' => 11,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 20,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-30 16:56:00'
            ],
            [
                'id' => 11,
                'menu_name' => 'User Master',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 9,
                's_order' => 13,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 23,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-16 17:51:44'
            ],
            [
                'id' => 12,
                'menu_name' => 'Media',
                'icon_class' => 'fa fa-image',
                'parent_id' => 2,
                's_order' => 28,
                'class_id' => 'title',
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 13,
                'menu_name' => 'View File',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 12,
                's_order' => 29,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 29,
                'tab_same_new' => 11,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-16 17:52:38'
            ],
            [
                'id' => 14,
                'menu_name' => 'Front Menu',
                'icon_class' => 'fas fa-folder-open',
                'parent_id' => 2,
                's_order' => 30,
                'class_id' => 'title',
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 15,
                'menu_name' => 'Menu Modules',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 14,
                's_order' => 31,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 16,
                'menu_name' => 'Top Menu',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 14,
                's_order' => 33,
                'class_id' => NULL,
                'params' => '{"type":"Top Menus"}',
                'fk_tbl_acl_permission_id' => 41,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-23 14:09:22'
            ],
            [
                'id' => 17,
                'menu_name' => 'Bottom Menu',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 14,
                's_order' => 34,
                'class_id' => NULL,
                'params' => '{"type":"Bottom Menus"}',
                'fk_tbl_acl_permission_id' => 41,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-23 14:10:08'
            ],
            [
                'id' => 18,
                'menu_name' => 'End Menu',
                'icon_class' => 'fa fa-cog',
                'parent_id' => 0,
                's_order' => 42,
                'class_id' => 'title',
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 19,
                'menu_name' => 'Footer Menu',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 14,
                's_order' => 35,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 20,
                'menu_name' => 'Header Menu',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 14,
                's_order' => 32,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 21,
                'menu_name' => 'Sidebar Menu',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 14,
                's_order' => 36,
                'class_id' => NULL,
                'params' => '{"type":"Side Menus"}',
                'fk_tbl_acl_permission_id' => 41,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-23 14:10:30'
            ],
            [
                'id' => 22,
                'menu_name' => 'Social Link',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 2,
                's_order' => 21,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 35,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-16 18:30:26'
            ],
            [
                'id' => 23,
                'menu_name' => 'Pages',
                'icon_class' => 'fa fa-file',
                'parent_id' => 2,
                's_order' => 25,
                'class_id' => 'title',
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 24,
                'menu_name' => 'Page Master',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 23,
                's_order' => 26,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 32,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-16 17:52:02'
            ],
            [
                'id' => 25,
                'menu_name' => 'Manage Feedback',
                'icon_class' => 'fa fa-users',
                'parent_id' => 23,
                's_order' => 27,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 26,
                'menu_name' => 'Sidebar Menu',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 2,
                's_order' => 37,
                'class_id' => 'title',
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 27,
                'menu_name' => 'Sidebar List',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 26,
                's_order' => 38,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 28,
                'menu_name' => 'Settings',
                'icon_class' => 'fa fa-cog',
                'parent_id' => 2,
                's_order' => 39,
                'class_id' => 'title',
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 29,
                'menu_name' => 'Website Setting',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 28,
                's_order' => 40,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 30,
                'menu_name' => 'Calendar Setting',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 28,
                's_order' => 41,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-06 07:38:55',
                'updated_at' => '2023-11-06 07:38:55'
            ],
            [
                'id' => 31,
                'menu_name' => 'Manage Slider',
                'icon_class' => 'fas fa-folder-open',
                'parent_id' => 2,
                's_order' => 22,
                'class_id' => 'title',
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-26 18:40:33',
                'updated_at' => '2023-11-26 18:40:33'
            ],
            [
                'id' => 32,
                'menu_name' => 'Top Slider',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 31,
                's_order' => 23,
                'class_id' => NULL,
                'params' => '{"type":"Top Slider"}',
                'fk_tbl_acl_permission_id' => 38,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-26 18:40:55',
                'updated_at' => '2023-11-27 13:05:50'
            ],
            [
                'id' => 33,
                'menu_name' => 'Bottom Slider',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 31,
                's_order' => 24,
                'class_id' => NULL,
                'params' => '{"type":"Bottom Slider"}',
                'fk_tbl_acl_permission_id' => 38,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-27 13:06:23',
                'updated_at' => '2023-11-27 13:06:23'
            ],
            [
                'id' => 34,
                'menu_name' => 'Office Onboarding',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 2,
                's_order' => 9,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 46,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-11-29 17:30:10',
                'updated_at' => '2023-11-29 17:30:10'
            ],
            [
                'id' => 35,
                'menu_name' => 'Manage Important Links',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 2,
                's_order' => 20,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 49,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-12-05 15:20:23',
                'updated_at' => '2023-12-05 15:20:23'
            ],
            [
                'id' => 36,
                'menu_name' => 'Course Creation',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 39,
                's_order' => 19,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 52,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-12-07 21:45:00',
                'updated_at' => '2023-12-20 12:38:05'
            ],
            [
                'id' => 37,
                'menu_name' => 'Additional Charge',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 9,
                's_order' => 12,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 55,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-12-18 12:37:19',
                'updated_at' => '2023-12-18 12:37:19'
            ],
            [
                'id' => 38,
                'menu_name' => 'Create Category',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 39,
                's_order' => 15,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 58,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-12-20 12:37:02',
                'updated_at' => '2023-12-21 13:14:57'
            ],
            [
                'id' => 39,
                'menu_name' => 'Course Management',
                'icon_class' => 'fas fa-folder-open',
                'parent_id' => 2,
                's_order' => 14,
                'class_id' => 'title',
                'params' => NULL,
                'fk_tbl_acl_permission_id' => NULL,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-12-20 12:37:31',
                'updated_at' => '2023-12-20 12:39:19'
            ],
            [
                'id' => 40,
                'menu_name' => 'Category Course',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 39,
                's_order' => 16,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 61,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-12-21 13:30:53',
                'updated_at' => '2023-12-21 13:30:53'
            ],
            [
                'id' => 41,
                'menu_name' => 'Course Assign to User',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 39,
                's_order' => 18,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 64,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2023-12-21 17:04:54',
                'updated_at' => '2023-12-21 17:05:11'
            ],
            [
                'id' => 42,
                'menu_name' => 'Course Configurations',
                'icon_class' => 'fa fa-hand-point-right',
                'parent_id' => 39,
                's_order' => 17,
                'class_id' => NULL,
                'params' => NULL,
                'fk_tbl_acl_permission_id' => 67,
                'tab_same_new' => 1,
                'is_active' => 1,
                'created_at' => '2024-01-02 11:56:33',
                'updated_at' => '2024-01-02 11:56:33'
            ],
        ];
        AdminMenu::insert($admin_menus);
        JsonService::createAdminSidebarMenuJson();
    }
}
